version: '3.7'
services: 
  opencatd:
    image: hushuozhi/opencatd-open
    container_name: opencatd-open 
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /etc/opencatd:/app/db
